---
output: github_document
---

# 2025 March Madness Forecast

This repository contains the code for fitting a dynamic Bayesian model of NCAA team performance and simulating potential March Madness outcomes based on the results.

## outline

#### Data

See the `R/data/` and `data/` directories.

#### Model

use the bivariate poisson to model score outcomes

$$
\begin{align*}
S_h &= Y_0 + Y_h \\
S_a &= Y_0 + Y_a \\
Y_0 &\sim \text{Poisson}(\lambda_0) \\
Y_h &\sim \text{Poisson}(\lambda_h) \\
Y_a &\sim \text{Poisson}(\lambda_a) \\
\log(\lambda_h) &= \beta_{a,t[h]} - \beta_{d,t[a]} \\
\log(\lambda_a) &= \beta_{a,t[a]} - \beta_{d,t[h]} \\
\log(\lambda_0) &= \gamma \\ 
\beta_{a,t} &= \alpha_a + \eta_{a,t} \sigma_a \\
\beta_{d,t} &= \alpha_d + \eta_{d,t} \sigma_d
\end{align*}
$$

Possibly convert to a MVN for attack/defense strength, add in time-varying parameters, other predictors (home advantage, game-level random effects, overtime), but that gets to the basic structure.

> Note: the bivariate poisson pmf can be resolved as `target += poisson_lpmf(S_h | lambda_0 + lambda_h) + poisson_lpmf(S_a | lambda_0 + lambda_a);`, since the sum of two poissons is also poisson. The encoding above, however, ensures that the generating function displays the correlated nature in forward evaluation.

Need to figure out:

* bivariate_poisson_lpmf
* mid-season updates?
  * don't refit the entire model lol
  * posterior -> prior extraction
  * half normal extraction

#### Simulation

* Part of model? Or separate & pass in model output as data?
* Individual game is easy
* Future matchups is somewhat difficult (array indexing hell)
* Ragged-array problem --- how to handle completed games & future games?

#### UI

* Ideally, big interactive bracket 
* Can also do a big table with:
  * tabs for each round
  * greyed out when eliminated
  * Prob of making it to: Round of 32, Sweet 16, Elite 8, Final 4, Championship, Winning
  
## Links

* [Paper on bivariate poisson for modeling soccer outcomes](https://link.springer.com/content/pdf/10.1007/s10182-021-00413-9.pdf)
* [Repo for simulating tournament advancement](https://github.com/lbenz730/intl_soccer_2024)
* [Bivariate poisson in Stan](https://discourse.mc-stan.org/t/loo-and-loglikelihood-calculation-for-bivariate-poisson/28648)
* [ESPN API links](https://gist.github.com/akeaswaran/b48b02f1c94f873c6655e7129910fc3b)
